---
- name: Use all Roles
  hosts: all

  pre_tasks:
    - name: Load all variable files
      include_vars: "{{ item }}"
      loop: "{{ lookup('fileglob', playbook_dir + '/vars/*.yml', wantlist=True) }}"
      loop_control:
        label: "{{ item | basename }}"
      tags: always
      run_once: true

  roles:
    - role: role-kube_init
    - role: role-awxconfig
